[package]
name = "paperless-ngx-copier"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
serde_json = "1.0.135"
serde = { version = "1.0", features = ["derive"] }
